import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "lawords.csv"

EXAMPLES = {
    "Abbildung": "Eine lineare Abbildung ordnet jedem Eingabevektor genau einen Ausgabevektor zu.（线性映射把每个输入向量对应到唯一的输出向量。）",
    "Abbildungen": "Lineare Abbildungen erhalten Addition und Skalarmultiplikation.（线性映射保持加法和数乘。）",
    "allgemeine Lösung": "Die allgemeine Lösung eines linearen Gleichungssystems besteht aus einer speziellen Lösung plus allen Lösungen des homogenen Systems.（线性方程组的通解由一个特解加上齐次解集组成。）",
    "Ausgangsmatrix": "Bei Zeilenumformungen vergleicht man die Ausgangsmatrix mit der reduzierten Matrix.（做行变换时，要比较初始矩阵和化简后的矩阵。）",
    "B-Koordinaten": "Die B-Koordinaten eines Vektors geben an, mit welchen Koeffizienten die Basisvektoren aus B kombiniert werden.（向量的B基坐标表示用B中基向量线性组合时的系数。）",
    "Basis": "Eine Basis ist ein linear unabhängiges Erzeugendensystem eines Vektorraums.（基是向量空间中线性无关且能张成全空间的一组向量。）",
    "Basis-Funktionen": "In einem Funktionenraum können Basis-Funktionen andere Funktionen durch Linearkombinationen annähern.（在函数空间中，基函数可以通过线性组合近似其他函数。）",
    "Basisdarstellung": "Die Basisdarstellung schreibt einen Vektor als Linearkombination der Basisvektoren.（基表示就是把向量写成基向量的线性组合。）",
    "Basismatrizen": "Basismatrizen können einen Matrixraum genauso aufspannen wie Basisvektoren einen Vektorraum.（基矩阵能张成矩阵空间，就像基向量张成向量空间一样。）",
    "Basissysteme": "Basissysteme erlauben eine eindeutige Koordinatendarstellung.（基系统使坐标表示唯一。）",
    "Basisvektoren": "Die Basisvektoren von $\\mathbb R^2$ können zum Beispiel $e_1=(1,0)^T$ und $e_2=(0,1)^T$ sein.（$\\mathbb R^2$ 的基向量可以是 $e_1=(1,0)^T$ 和 $e_2=(0,1)^T$。）",
    "Basiswechsel": "Beim Basiswechsel werden Koordinaten desselben Vektors von einer Basis in eine andere umgerechnet.（换基是把同一个向量在一组基下的坐标换算到另一组基下。）",
    "Batch-Skalarprodukt": "Ein Batch-Skalarprodukt berechnet mehrere Skalarprodukte gleichzeitig, etwa in einer Datenmatrix.（批量内积可以一次计算多个内积，例如在数据矩阵中。）",
    "Bernoulli-Ungleichung": "Die Bernoulli-Ungleichung liefert eine Abschätzung für Potenzen und wird oft in Beweisen benutzt.（伯努利不等式给出幂的估计，常用于证明。）",
    "bijektiv": "Eine bijektive lineare Abbildung ist sowohl injektiv als auch surjektiv und besitzt eine Umkehrabbildung.（双射线性映射既单射又满射，因此有逆映射。）",
    "Bild": "Das Bild einer Matrix ist die Menge aller Vektoren, die als $Ax$ entstehen können.（矩阵的像是所有可以写成 $Ax$ 的向量集合。）",
    "Cauchy-Schwarz-Ungleichung": "Die Cauchy-Schwarz-Ungleichung besagt $|\\langle u,v\\rangle|\\le \\|u\\|\\|v\\|$.（柯西-施瓦茨不等式说明 $|\\langle u,v\\rangle|\\le \\|u\\|\\|v\\|$。）",
    "charakteristische Gleichung": "Die charakteristische Gleichung $\\det(A-\\lambda I)=0$ bestimmt die Eigenwerte von $A$.（特征方程 $\\det(A-\\lambda I)=0$ 用来求矩阵 $A$ 的特征值。）",
    "charakteristisches Polynom": "Die Nullstellen des charakteristischen Polynoms sind die Eigenwerte der Matrix.（特征多项式的零点就是矩阵的特征值。）",
    "Definitheit": "Die Definitheit einer quadratischen Form wird über die Vorzeichen ihrer Eigenwerte entschieden.（二次型的定性由其特征值符号决定。）",
    "Definitionsbereich": "Der Definitionsbereich einer linearen Abbildung ist der Vektorraum, aus dem die Eingaben stammen.（线性映射的定义域是输入向量所在的向量空间。）",
    "Determinante": "Die Determinante misst, wie eine Matrix Volumen skaliert und ob sie invertierbar ist.（行列式衡量矩阵如何缩放体积，并判断矩阵是否可逆。）",
    "Determinanten": "Determinanten von Dreiecksmatrizen erhält man durch Multiplikation der Diagonaleinträge.（三角矩阵的行列式等于对角线元素的乘积。）",
    "Diagonale": "Die Diagonale einer Matrix besteht aus den Einträgen $a_{11},a_{22},\\ldots$.（矩阵的对角线由 $a_{11},a_{22},\\ldots$ 这些元素组成。）",
    "Diagonaleinträge": "Bei einer Dreiecksmatrix ist die Determinante das Produkt der Diagonaleinträge.（三角矩阵的行列式是所有对角线元素的乘积。）",
    "Diagonalen": "In einer Diagonalmatrix dürfen außerhalb der Diagonalen nur Nullen stehen.（对角矩阵在对角线以外的位置必须为零。）",
    "diagonalisierbar": "Eine Matrix ist diagonalisierbar, wenn sie eine Basis aus Eigenvektoren besitzt.（如果矩阵有一组特征向量基，它就是可对角化的。）",
    "Diagonalisierung": "Die Diagonalisierung schreibt eine Matrix in der Form $A=PDP^{-1}$.（对角化把矩阵写成 $A=PDP^{-1}$ 的形式。）",
    "Diagonalmatrix": "In einer Diagonalmatrix stehen die wichtigen Skalierungsfaktoren auf der Diagonale.（对角矩阵的重要缩放因子位于对角线上。）",
    "Dimension": "Die Dimension eines Vektorraums ist die Anzahl der Vektoren in einer Basis.（向量空间的维数是一组基中向量的个数。）",
    "Drehmatrix": "Eine Drehmatrix rotiert Vektoren um den Ursprung, ohne ihre Länge zu verändern.（旋转矩阵绕原点旋转向量，并保持长度不变。）",
    "Dreiecksmatrix": "Bei einer Dreiecksmatrix stehen alle Einträge unter oder über der Diagonale auf Null.（三角矩阵在主对角线的一侧全为零。）",
    "Eigenraum": "Der Eigenraum zu $\\lambda$ besteht aus allen Vektoren mit $Ax=\\lambda x$.（属于 $\\lambda$ 的特征空间由所有满足 $Ax=\\lambda x$ 的向量组成。）",
    "Eigenräume": "Eigenräume zu verschiedenen Eigenwerten schneiden sich nur im Nullvektor.（不同特征值对应的特征空间只在零向量处相交。）",
    "Eigenvektor": "Ein Eigenvektor ändert unter $A$ nur seine Länge oder Richtungsvorzeichen, nicht seine Richtungslinie.（特征向量在矩阵作用下只改变长度或方向符号，不改变所在直线。）",
    "Eigenvektoren": "Eigenvektoren bilden bei der Diagonalisierung die Spalten der Matrix $P$.（对角化时，特征向量构成矩阵 $P$ 的列。）",
    "Eigenwert": "Der Eigenwert $\\lambda$ gibt an, mit welchem Faktor ein Eigenvektor skaliert wird.（特征值 $\\lambda$ 表示特征向量被缩放的倍数。）",
    "Eigenwertgleichung": "Die Eigenwertgleichung folgt aus $Ax=\\lambda x$ und wird zu $(A-\\lambda I)x=0$.（特征值方程来自 $Ax=\\lambda x$，可化为 $(A-\\lambda I)x=0$。）",
    "Eigenwerte": "Bei einer Dreiecksmatrix sind die Eigenwerte die Diagonaleinträge.（三角矩阵的特征值就是对角线元素。）",
    "Eigenwertproblem": "Im Eigenwertproblem sucht man Zahlen $\\lambda$ und Vektoren $x\\ne0$ mit $Ax=\\lambda x$.（特征值问题就是寻找满足 $Ax=\\lambda x$ 的数 $\\lambda$ 和非零向量 $x$。）",
    "Einheitsmatrix": "Die Einheitsmatrix $I$ erfüllt $AI=IA=A$.（单位矩阵 $I$ 满足 $AI=IA=A$。）",
    "Einheitsvektor": "Ein Einheitsvektor hat Norm $1$ und beschreibt nur eine Richtung.（单位向量范数为 $1$，只表示方向。）",
    "Einheitsvektoren": "Die Standard-Einheitsvektoren bilden die Standardbasis von $\\mathbb R^n$.（标准单位向量构成 $\\mathbb R^n$ 的标准基。）",
    "elementare Zeilenoperation": "Elementare Zeilenoperationen verändern ein Gleichungssystem, ohne seine Lösungsmenge zu verlieren.（初等行变换改变方程组的写法，但不丢失解集。）",
    "Endomorphismus": "Ein Endomorphismus ist eine lineare Abbildung von einem Vektorraum in sich selbst.（自同态是从一个向量空间到它自身的线性映射。）",
    "Erzeugendensystem": "Ein Erzeugendensystem spannt den ganzen Vektorraum auf.（生成系能够张成整个向量空间。）",
    "erweiterte Matrix": "Eine erweiterte Matrix hängt die rechte Seite eines Gleichungssystems an die Koeffizientenmatrix an.（增广矩阵把方程组右端项接在系数矩阵后面。）",
    "Faktorisierung": "Eine Faktorisierung zerlegt eine Matrix oder ein Polynom in einfachere Bausteine.（分解把矩阵或多项式拆成更简单的组成部分。）",
    "freie Variable": "Eine freie Variable entsteht, wenn eine Spalte keinen Pivot besitzt.（某列没有主元时，对应变量就是自由变量。）",
    "Frobenius-Skalarprodukt": "Das Frobenius-Skalarprodukt von Matrizen addiert die Produkte der entsprechenden Einträge.（Frobenius内积把两个矩阵对应元素相乘后求和。）",
    "Gauß-Elimination": "Die Gauß-Elimination bringt ein lineares Gleichungssystem in Zeilenstufenform.（高斯消元把线性方程组化为行阶梯形。）",
    "Gauß-Jordan-Verfahren": "Das Gauß-Jordan-Verfahren reduziert weiter bis zur reduzierten Zeilenstufenform.（高斯-约当法进一步化到简化行阶梯形。）",
    "Gegenbeispiel": "Ein Gegenbeispiel widerlegt eine allgemeine Aussage mit einem einzigen konkreten Fall.（反例用一个具体情况推翻一般命题。）",
    "geometrische Vielfachheit": "Die geometrische Vielfachheit ist die Dimension des Eigenraums.（几何重数是特征空间的维数。）",
    "Gleichungssystem": "Ein Gleichungssystem fasst mehrere Gleichungen zusammen, die gleichzeitig erfüllt sein müssen.（方程组把多个必须同时成立的方程放在一起。）",
    "Gram-Schmidt": "Das Gram-Schmidt-Verfahren verwandelt eine Basis in eine orthogonale Basis.（Gram-Schmidt方法把一组基变成正交基。）",
    "Gram-Schmidt-Verfahren": "Im Gram-Schmidt-Verfahren zieht man nacheinander Projektionen ab.（Gram-Schmidt方法逐步减去投影部分。）",
    "Hauptachsentransformation": "Die Hauptachsentransformation entfernt Mischterme einer quadratischen Form.（主轴变换消去二次型中的混合项。）",
    "homogen": "Ein homogenes lineares Gleichungssystem hat rechte Seite Null.（齐次线性方程组的右端项为零。）",
    "homogene Gleichungssysteme": "Homogene Gleichungssysteme besitzen immer mindestens die triviale Lösung.（齐次方程组至少有平凡解。）",
    "homogenes Gleichungssystem": "Die Lösungsmenge eines homogenen Gleichungssystems ist ein Unterraum.（齐次方程组的解集是子空间。）",
    "Hyperebene": "Eine Hyperebene ist in $\\mathbb R^n$ ein Unterraum oder affiner Raum der Dimension $n-1$.（超平面是在 $\\mathbb R^n$ 中维数为 $n-1$ 的子空间或仿射空间。）",
    "Identitätsmatrix": "Die Identitätsmatrix wirkt wie die Zahl $1$ bei der Matrixmultiplikation.（单位矩阵在矩阵乘法中类似数字 $1$。）",
    "indefinit": "Eine quadratische Form ist indefinit, wenn sie positive und negative Werte annimmt.（二次型若既能取正值又能取负值，就是不定的。）",
    "inhomogen": "Ein inhomogenes Gleichungssystem hat eine rechte Seite, die nicht überall Null ist.（非齐次方程组的右端项不全为零。）",
    "inhomogene Gleichungssysteme": "Inhomogene Gleichungssysteme werden als spezielle Lösung plus homogene Lösung beschrieben.（非齐次方程组的解可写成特解加齐次解。）",
    "inhomogenes Gleichungssystem": "Ein inhomogenes Gleichungssystem muss nicht durch den Nullvektor gelöst werden.（非齐次方程组不一定由零向量解出。）",
    "injektiv": "Eine lineare Abbildung ist injektiv, wenn ihr Kern nur aus dem Nullvektor besteht.（线性映射若核只有零向量，则为单射。）",
    "inneres Produkt": "Ein inneres Produkt verallgemeinert das Skalarprodukt und definiert Winkel und Längen.（内积推广点积，并定义角度与长度。）",
    "Interpolation": "Bei der Interpolation sucht man eine Funktion, die vorgegebene Punkte exakt trifft.（插值寻找一条准确穿过给定点的函数。）",
    "invarianter Unterraum": "Ein invarianter Unterraum wird durch eine lineare Abbildung wieder in sich selbst abgebildet.（不变子空间在线性映射作用后仍落在自身内。）",
    "Inverse": "Die Inverse macht die Wirkung einer invertierbaren Matrix rückgängig.（逆矩阵撤销一个可逆矩阵的作用。）",
    "inverse Matrix": "Eine inverse Matrix erfüllt $AA^{-1}=A^{-1}A=I$.（逆矩阵满足 $AA^{-1}=A^{-1}A=I$。）",
    "invertierbar": "Eine Matrix ist invertierbar genau dann, wenn ihre Determinante nicht Null ist.（矩阵可逆当且仅当行列式不为零。）",
    "Kern": "Der Kern von $A$ besteht aus allen Vektoren $x$ mit $Ax=0$.（矩阵 $A$ 的核由所有满足 $Ax=0$ 的向量组成。）",
    "Kernbasis": "Eine Kernbasis ist eine Basis des Lösungsraums von $Ax=0$.（核空间的一组基就是 $Ax=0$ 解空间的一组基。）",
    "Kernes": "Die Dimension des Kernes ist die Anzahl der freien Variablen.（核的维数等于自由变量个数。）",
    "Kernraum": "Der Kernraum ist ein anderer Name für den Kern einer linearen Abbildung.（核空间是线性映射的核的另一种说法。）",
    "Kerns": "Die Basis des Kerns beschreibt alle Lösungen von $Ax=0$.（核的一组基描述 $Ax=0$ 的全部解。）",
    "Koeffizient": "Ein Koeffizient ist der Zahlenfaktor vor einer Variablen oder einem Basisvektor.（系数是变量或基向量前面的数字因子。）",
    "Koeffizienten": "In einer Matrix sammeln die Koeffizienten die Faktoren der Unbekannten.（矩阵中的系数收集了未知量前面的因子。）",
    "Koeffizientenmatrix": "Die Koeffizientenmatrix enthält nur die Faktoren der Unbekannten, nicht die rechte Seite.（系数矩阵只包含未知量系数，不包含右端项。）",
    "Koeffizientenvektor": "Ein Koeffizientenvektor enthält die Gewichte einer Linearkombination.（系数向量包含线性组合中的权重。）",
    "Kofaktor": "Ein Kofaktor ist ein vorzeichenbehafteter Minor in der Determinantenentwicklung.（余因子是带符号的子式。）",
    "Kofaktoren": "Kofaktoren werden bei der Entwicklung einer Determinante entlang einer Zeile oder Spalte benutzt.（余因子用于沿行或列展开行列式。）",
    "Kofaktorenentwicklung": "Die Kofaktorenentwicklung berechnet eine Determinante durch kleinere Determinanten.（余因子展开通过更小的行列式计算行列式。）",
    "Kofaktorentwicklung": "Bei der Kofaktorentwicklung wählt man am besten eine Zeile oder Spalte mit vielen Nullen.（余子式展开最好选择零最多的行或列。）",
    "Koordinate": "Eine Koordinate ist ein Koeffizient eines Vektors bezüglich einer Basis.（坐标是向量相对于某组基的系数。）",
    "Koordinaten": "Koordinaten hängen von der gewählten Basis ab.（坐标依赖于所选基。）",
    "Koordinatensystem": "Ein Koordinatensystem legt fest, wie Punkte oder Vektoren beschrieben werden.（坐标系规定如何描述点或向量。）",
    "Koordinatensysteme": "Verschiedene Koordinatensysteme können denselben Vektor unterschiedlich darstellen.（不同坐标系会用不同坐标表示同一向量。）",
    "Koordinatensystemen": "Beim Rechnen in Koordinatensystemen muss die Basis klar sein.（在坐标系中计算时必须明确基。）",
    "Koordinatensystems": "Die Achsen eines Koordinatensystems bestimmen die Richtungen der Koordinaten.（坐标系的坐标轴决定坐标方向。）",
    "Koordinatenvektor": "Der Koordinatenvektor sammelt die Koordinaten eines Vektors bezüglich einer Basis.（坐标向量收集向量在某组基下的坐标。）",
    "Kosinus des Winkels": "Der Kosinus des Winkels wird durch $\\frac{u\\cdot v}{\\|u\\|\\|v\\|}$ berechnet.（夹角余弦由 $\\frac{u\\cdot v}{\\|u\\|\\|v\\|}$ 计算。）",
    "Kovarianzmatrix": "Die Kovarianzmatrix beschreibt gemeinsame Streuung mehrerer Variablen.（协方差矩阵描述多个变量的共同变动。）",
    "least squares": "Least squares bedeutet, die Summe der quadrierten Fehler zu minimieren.（最小二乘表示最小化误差平方和。）",
    "Legendre-Polynom-Basen": "Legendre-Polynom-Basen sind orthogonale Basen in bestimmten Funktionenräumen.（勒让德多项式基是某些函数空间中的正交基。）",
    "Legendre-Polynome": "Legendre-Polynome sind Beispiele orthogonaler Polynome.（勒让德多项式是正交多项式的例子。）",
    "Legendrepolynome": "Legendrepolynome werden zur orthogonalen Approximation von Funktionen verwendet.（勒让德多项式可用于函数的正交逼近。）",
    "linear abhängig": "Vektoren sind linear abhängig, wenn einer als Linearkombination der anderen geschrieben werden kann.（若某个向量能由其他向量线性组合得到，则这些向量线性相关。）",
    "linear unabhängig": "Vektoren sind linear unabhängig, wenn nur die triviale Linearkombination den Nullvektor ergibt.（只有平凡线性组合得到零向量时，向量组线性无关。）",
    "lineare Abbildung": "Eine lineare Abbildung erfüllt $T(u+v)=T(u)+T(v)$ und $T(cu)=cT(u)$.（线性映射满足加法保持和数乘保持。）",
    "lineare Abbildungen": "Lineare Abbildungen können durch Matrizen dargestellt werden, wenn Basen gewählt sind.（选定基后，线性映射可用矩阵表示。）",
    "lineare Algebra": "Lineare Algebra untersucht Vektoren, Matrizen, lineare Abbildungen und ihre Strukturen.（线性代数研究向量、矩阵、线性映射及其结构。）",
    "lineare Funktion": "Eine lineare Funktion hat in diesem Kontext keine Produkte oder Potenzen von Variablen.（线性函数在这里不含变量乘积或变量高次幂。）",
    "lineare Funktionen": "Lineare Funktionen erhalten die Struktur von Addition und Skalarmultiplikation.（线性函数保持加法和数乘结构。）",
    "lineare Gleichung": "Eine lineare Gleichung enthält Unbekannte nur in erster Potenz.（线性方程中的未知量只以一次形式出现。）",
    "lineare Operationen": "Lineare Operationen passen zu Addition und Skalarmultiplikation.（线性运算与加法和数乘相容。）",
    "lineare Probleme": "Lineare Probleme lassen sich häufig durch Matrizen und Vektoren formulieren.（线性问题常可用矩阵和向量表示。）",
    "lineare Regression": "Lineare Regression passt ein lineares Modell möglichst gut an Daten an.（线性回归用线性模型尽量拟合数据。）",
    "lineare Struktur": "Eine lineare Struktur erlaubt Rechnen mit Summen und Vielfachen.（线性结构允许用和与倍数进行计算。）",
    "lineare Transformation": "Eine lineare Transformation ist eine lineare Abbildung zwischen Vektorräumen.（线性变换是向量空间之间的线性映射。）",
    "lineare Transformationen": "Lineare Transformationen können Strecken, Drehen, Spiegeln oder Projizieren beschreiben.（线性变换可以描述拉伸、旋转、反射或投影。）",
    "lineare Unabhängigkeit": "Lineare Unabhängigkeit bedeutet, dass kein Vektor überflüssig ist.（线性无关表示没有向量是多余的。）",
    "lineares Gleichungssystem": "Ein lineares Gleichungssystem kann als Matrixgleichung $Ax=b$ geschrieben werden.（线性方程组可写成矩阵方程 $Ax=b$。）",
    "lineares Modell": "Ein lineares Modell beschreibt Daten mit Parametern, die linear auftreten.（线性模型用线性出现的参数描述数据。）",
    "Linearität": "Linearität fasst Additivität und Homogenität zusammen.（线性包含可加性和齐次性。）",
    "Linearkombination": "Eine Linearkombination ist eine Summe von Vielfachen gegebener Vektoren.（线性组合是若干给定向量倍数的和。）",
    "Linearkombinationen": "Linearkombinationen beschreiben alle Vektoren im Spann einer Menge.（线性组合描述一个集合张成空间中的所有向量。）",
    "Lösungsmenge": "Die Lösungsmenge enthält alle Vektoren, die ein Gleichungssystem erfüllen.（解集包含所有满足方程组的向量。）",
    "Lösungsmengen": "Lösungsmengen homogener Systeme sind Unterräume.（齐次系统的解集是子空间。）",
    "Lösungsraum": "Der Lösungsraum eines homogenen Systems ist der Kern der Koeffizientenmatrix.（齐次系统的解空间是系数矩阵的核。）",
    "Markovkette": "Eine Markovkette beschreibt Zustandsübergänge mit einer stochastischen Matrix.（马尔可夫链用随机矩阵描述状态转移。）",
    "Markovketten": "Bei Markovketten interessiert oft der stationäre Zustand.（马尔可夫链中常关心稳定状态。）",
    "Matrix": "Eine Matrix ist ein rechteckiges Zahlenschema, das lineare Abbildungen darstellen kann.（矩阵是矩形数表，可表示线性映射。）",
    "Matrix-Vektor": "Ein Matrix-Vektor-Produkt ist eine Linearkombination der Spalten der Matrix.（矩阵-向量乘积是矩阵列向量的线性组合。）",
    "Matrix-Vektor-Multiplikation": "Bei der Matrix-Vektor-Multiplikation liefern die Einträge des Vektors die Gewichte der Spalten.（矩阵-向量乘法中，向量元素给出列向量的权重。）",
    "Matrix-Vektor-Multiplikationen": "Matrix-Vektor-Multiplikationen treten in jedem linearen Gleichungssystem $Ax=b$ auf.（矩阵-向量乘法出现在每个线性方程组 $Ax=b$ 中。）",
    "Matrix-Vektor-Produkt": "Das Matrix-Vektor-Produkt $Ax$ liegt im Spaltenraum von $A$.（矩阵-向量乘积 $Ax$ 位于 $A$ 的列空间中。）",
    "Matrixmultiplikation": "Matrixmultiplikation ist im Allgemeinen nicht kommutativ.（矩阵乘法一般不满足交换律。）",
    "Matrixprodukt": "Das Matrixprodukt $AB$ beschreibt die Hintereinanderausführung zweier linearer Abbildungen.（矩阵乘积 $AB$ 表示两个线性映射的复合。）",
    "Norm": "Die Norm misst die Länge eines Vektors.（范数衡量向量的长度。）",
    "Normalengleichung": "Die Normalengleichung $A^TAx=A^Tb$ liefert die Least-Squares-Lösung.（正规方程 $A^TAx=A^Tb$ 给出最小二乘解。）",
    "Normalgleichungen": "Normalgleichungen entstehen, wenn der Residualvektor orthogonal zum Spaltenraum sein soll.（正规方程来自残差与列空间正交这一条件。）",
    "Normalisierung": "Normalisierung skaliert einen Vektor auf Norm $1$.（归一化把向量缩放到范数为 $1$。）",
    "normalisiert": "Ein normalisierter Vektor hat Norm $1$.（归一化后的向量范数为 $1$。）",
    "Nullmatrix": "Die Nullmatrix hat nur Nullen als Einträge.（零矩阵的所有元素都是零。）",
    "Nullraum": "Der Nullraum ist die Menge aller Lösungen von $Ax=0$.（零空间是 $Ax=0$ 的所有解组成的集合。）",
    "Nullstelle": "Eine Nullstelle eines Polynoms ist ein Wert, bei dem das Polynom Null wird.（多项式的零点是使多项式等于零的值。）",
    "Nullstellen": "Die Nullstellen des charakteristischen Polynoms sind die Eigenwerte.（特征多项式的零点就是特征值。）",
    "Nullvektor": "Der Nullvektor ist das neutrale Element der Vektoraddition.（零向量是向量加法的中性元。）",
    "Nullvektoren": "In einem Vektorraum gibt es genau einen Nullvektor, auch wenn er verschieden dargestellt wird.（一个向量空间中只有一个零向量，即使表示方式不同。）",
    "obere Dreiecksmatrix": "Bei einer oberen Dreiecksmatrix stehen unter der Diagonale nur Nullen.（上三角矩阵在主对角线下方全为零。）",
    "orthogonal": "Zwei Vektoren sind orthogonal, wenn ihr Skalarprodukt Null ist.（两个向量内积为零时正交。）",
    "Orthogonalbasis": "Eine Orthogonalbasis besteht aus paarweise orthogonalen Basisvektoren.（正交基由两两正交的基向量组成。）",
    "orthogonale Diagonalisierung": "Bei der orthogonalen Diagonalisierung gilt $A=QDQ^T$.（正交对角化中有 $A=QDQ^T$。）",
    "orthogonale Matrix": "Eine orthogonale Matrix erfüllt $Q^TQ=I$ und erhält Längen.（正交矩阵满足 $Q^TQ=I$ 并保持长度。）",
    "orthogonale Projektion": "Die orthogonale Projektion liefert den nächstgelegenen Punkt in einem Unterraum.（正交投影给出子空间中离目标最近的点。）",
    "orthogonales Komplement": "Das orthogonale Komplement enthält alle Vektoren, die zu einem Unterraum orthogonal sind.（正交补包含所有与某子空间正交的向量。）",
    "orthonormal": "Eine orthonormale Familie ist orthogonal und besteht aus Einheitsvektoren.（标准正交族既正交又由单位向量组成。）",
    "Orthonormalbasis": "Eine Orthonormalbasis macht Koordinatenberechnungen besonders einfach.（标准正交基让坐标计算特别简单。）",
    "PageRank": "PageRank nutzt einen stationären Eigenvektor einer stochastischen Matrix.（PageRank 使用随机矩阵的稳定特征向量。）",
    "Parameterdarstellung": "Eine Parameterdarstellung beschreibt unendlich viele Lösungen mit freien Variablen.（参数表示用自由变量描述无穷多解。）",
    "Parameterform": "In Parameterform werden Lösungen mit einem oder mehreren Parametern geschrieben.（参数形式用一个或多个参数写出解。）",
    "Permutationsmatrix": "Eine Permutationsmatrix vertauscht Koordinaten oder Zeilen.（置换矩阵用于交换坐标或行。）",
    "Pivot": "Ein Pivot ist der führende Eintrag einer Zeile in der Zeilenstufenform.（主元是行阶梯形中一行的首个非零元素。）",
    "positiv definit": "Eine Matrix ist positiv definit, wenn $x^TAx>0$ für alle $x\\ne0$ gilt.（若对所有非零 $x$ 都有 $x^TAx>0$，矩阵正定。）",
    "positiv semidefinit": "Positiv semidefinit bedeutet $x^TAx\\ge0$ für alle $x$.（半正定表示对所有 $x$ 都有 $x^TAx\\ge0$。）",
    "Projektionsmatrix": "Eine Projektionsmatrix erfüllt häufig $P^2=P$.（投影矩阵通常满足 $P^2=P$。）",
    "Projektion": "Eine Projektion zerlegt einen Vektor in einen Anteil im Unterraum und einen orthogonalen Fehler.（投影把向量分解为子空间中的部分和正交误差。）",
    "Projektionstheorem": "Das Projektionstheorem garantiert die beste Approximation in einem Unterraum.（投影定理保证子空间中的最佳近似。）",
    "QR-Zerlegung": "Die QR-Zerlegung schreibt eine Matrix als Produkt einer orthogonalen Matrix und einer Dreiecksmatrix.（QR分解把矩阵写成正交矩阵与三角矩阵的乘积。）",
    "quadratische Form": "Eine quadratische Form hat die Gestalt $x^TAx$ mit symmetrischer Matrix $A$.（二次型形如 $x^TAx$，其中 $A$ 是对称矩阵。）",
    "quadratische Formen": "Quadratische Formen beschreiben gekrümmte Flächen und Optimierungsprobleme.（二次型描述弯曲曲面和优化问题。）",
    "Rang": "Der Rang einer Matrix ist die Dimension ihres Spaltenraums.（矩阵的秩是其列空间的维数。）",
    "Rang-Nullität": "Rang-Nullität beschreibt die Aufteilung der Eingabedimension in Bild und Kern.（秩-零化度描述输入维数在像和核之间的分配。）",
    "Rang-Nullitätssatz": "Der Rang-Nullitätssatz lautet $\\operatorname{rang}(A)+\\dim\\ker(A)=n$.（秩-零化度定理为 $\\operatorname{rang}(A)+\\dim\\ker(A)=n$。）",
    "reduzierte Zeilenstufenform": "In reduzierter Zeilenstufenform ist jeder Pivot gleich $1$ und allein in seiner Spalte.（简化行阶梯形中每个主元为 $1$，且所在列其他元素为零。）",
    "Reflexion": "Eine Reflexion spiegelt Vektoren an einer Geraden oder Ebene.（反射把向量关于直线或平面镜像。）",
    "Residuum": "Das Residuum $r=b-A\\hat x$ ist der Fehlervektor in der Least-Squares-Aufgabe.（残差 $r=b-A\\hat x$ 是最小二乘问题中的误差向量。）",
    "Rotation": "Eine Rotation dreht Vektoren und wird durch eine orthogonale Matrix beschrieben.（旋转转动向量，可由正交矩阵描述。）",
    "Singulärwert": "Ein Singulärwert beschreibt, wie stark eine Matrix in einer Hauptachse streckt.（奇异值描述矩阵在某个主轴方向上的拉伸倍数。）",
    "Singulärwerte": "Singulärwerte sind die Quadratwurzeln der Eigenwerte von $A^TA$.（奇异值是 $A^TA$ 的特征值的平方根。）",
    "Singulärwertzerlegung": "Die Singulärwertzerlegung schreibt $A=U\\Sigma V^T$.（奇异值分解把矩阵写成 $A=U\\Sigma V^T$。）",
    "Skalar": "Ein Skalar ist eine Zahl, mit der ein Vektor multipliziert wird.（标量是用来乘向量的数。）",
    "Skalarmultiplikation": "Skalarmultiplikation streckt oder staucht einen Vektor.（数乘会拉伸或压缩向量。）",
    "Skalarprodukt": "Das Skalarprodukt misst, wie stark zwei Vektoren in dieselbe Richtung zeigen.（内积衡量两个向量同向的程度。）",
    "Spalten": "Die Spalten einer Matrix sind die Bilder der Standardbasisvektoren.（矩阵的列是标准基向量的像。）",
    "Spaltenbasis": "Eine Spaltenbasis besteht aus Pivotspalten der ursprünglichen Matrix.（列空间的一组基由原矩阵的主元列组成。）",
    "Spaltenraum": "Der Spaltenraum ist der Spann der Spalten einer Matrix.（列空间是矩阵所有列向量的张成空间。）",
    "Spaltenvektor": "Ein Spaltenvektor wird als eine Matrix mit nur einer Spalte geschrieben.（列向量可看作只有一列的矩阵。）",
    "Spaltenvektoren": "Spaltenvektoren einer Matrix erzeugen den Spaltenraum.（矩阵的列向量张成列空间。）",
    "Spann": "Der Spann einer Vektormenge enthält alle Linearkombinationen dieser Vektoren.（向量组的张成空间包含这些向量的所有线性组合。）",
    "Spektralsatz": "Der Spektralsatz sagt, dass reelle symmetrische Matrizen orthogonal diagonalisierbar sind.（谱定理说明实对称矩阵可正交对角化。）",
    "Spektralzerlegung": "Die Spektralzerlegung schreibt eine symmetrische Matrix als Summe gewichteter Projektionen.（谱分解把对称矩阵写成加权投影之和。）",
    "Spiegelung": "Eine Spiegelung ist eine lineare Abbildung mit Determinante oft gleich $-1$.（反射是一种线性映射，其行列式常为 $-1$。）",
    "stationärer Vektor": "Ein stationärer Vektor erfüllt $Pv=v$ für eine Markov-Matrix $P$.（稳定向量满足马尔可夫矩阵 $P$ 下的 $Pv=v$。）",
    "stationärer Zustand": "Ein stationärer Zustand bleibt nach Anwendung der Übergangsmatrix unverändert.（稳定状态在转移矩阵作用后保持不变。）",
    "stochastische Matrix": "In einer stochastischen Matrix beschreiben die Einträge Übergangswahrscheinlichkeiten.（随机矩阵的元素描述转移概率。）",
    "surjektiv": "Eine Abbildung ist surjektiv, wenn jedes Element des Zielraums getroffen wird.（若陪域中每个元素都能被映到，则映射是满射。）",
    "symmetrische Matrix": "Eine symmetrische Matrix erfüllt $A^T=A$.（对称矩阵满足 $A^T=A$。）",
    "Transformationsmatrix": "Eine Transformationsmatrix stellt eine lineare Transformation bezüglich gewählter Basen dar.（变换矩阵表示选定基下的线性变换。）",
    "transponierte Matrix": "Die transponierte Matrix entsteht durch Vertauschen von Zeilen und Spalten.（转置矩阵由行列互换得到。）",
    "Transposition": "Bei der Transposition wird aus der Zeile eine Spalte und aus der Spalte eine Zeile.（转置把行变列、列变行。）",
    "triviale Lösung": "Die triviale Lösung eines homogenen Systems ist der Nullvektor.（齐次系统的平凡解是零向量。）",
    "untere Dreiecksmatrix": "Bei einer unteren Dreiecksmatrix stehen oberhalb der Diagonale nur Nullen.（下三角矩阵在主对角线上方全为零。）",
    "Unterraum": "Ein Unterraum ist eine Teilmenge, die selbst wieder ein Vektorraum ist.（子空间是本身仍构成向量空间的子集。）",
    "Unterräume": "Schnittmengen von Unterräumen sind wieder Unterräume.（子空间的交集仍是子空间。）",
    "Untervektorraum": "Ein Untervektorraum muss den Nullvektor enthalten und unter Addition sowie Skalarmultiplikation abgeschlossen sein.（子向量空间必须包含零向量，并对加法和数乘封闭。）",
    "Vektor": "Ein Vektor ist ein Objekt, das addiert und mit Skalaren multipliziert werden kann.（向量是可以相加并可与标量相乘的对象。）",
    "Vektoren": "Vektoren können als Pfeile, Spalten oder abstrakte Elemente eines Vektorraums auftreten.（向量可以表现为箭头、列向量或向量空间中的抽象元素。）",
    "Vektorraum": "Ein Vektorraum ist eine Menge mit sinnvoller Addition und Skalarmultiplikation.（向量空间是带有合理加法和数乘的集合。）",
    "Vektorraums": "Die Dimension eines Vektorraums hängt nicht von der gewählten Basis ab.（向量空间的维数不依赖所选基。）",
    "Vielfachheit": "Die Vielfachheit beschreibt, wie oft ein Eigenwert als Nullstelle vorkommt.（重数描述特征值作为零点出现的次数。）",
    "Zeilen": "Zeilen einer Matrix entsprechen einzelnen Gleichungen in einem linearen Gleichungssystem.（矩阵的行对应线性方程组中的各个方程。）",
    "Zeilenoperation": "Eine Zeilenoperation ist ein Schritt der Gauß-Elimination.（行变换是高斯消元中的一步。）",
    "Zeilenoperationen": "Zeilenoperationen bringen eine Matrix in Zeilenstufenform.（行变换把矩阵化为行阶梯形。）",
    "Zeilenraum": "Der Zeilenraum ist der Spann der Zeilenvektoren einer Matrix.（行空间是矩阵行向量的张成空间。）",
    "Zeilenstufenform": "Die Zeilenstufenform macht Pivotpositionen und freie Variablen sichtbar.（行阶梯形让主元位置和自由变量变得清楚。）",
    "Zeilenumformung": "Eine Zeilenumformung verändert die Darstellung, aber bei erlaubten Operationen nicht die Lösungsmenge.（行变换改变表示形式，但允许操作不改变解集。）",
    "Zeilenvektor": "Ein Zeilenvektor wird als Matrix mit nur einer Zeile geschrieben.（行向量可看作只有一行的矩阵。）",
    "Zerlegung": "Eine Zerlegung wie QR oder SVD schreibt eine Matrix als Produkt einfacher Matrizen.（QR或SVD这类分解把矩阵写成简单矩阵的乘积。）",
    "Zielraum": "Der Zielraum ist der Raum, in dem die Werte einer Abbildung liegen sollen.（陪域是映射结果应该落入的空间。）",
}

EXAMPLES.update({
    "Abgeschlossenheit": "Abgeschlossenheit bedeutet, dass Summe und Skalarmultiplikation innerhalb der Menge bleiben.（封闭性表示加法和数乘后的结果仍留在集合内部。）",
    "Additivität": "Additivität einer linearen Abbildung bedeutet $T(u+v)=T(u)+T(v)$.（线性映射的可加性表示 $T(u+v)=T(u)+T(v)$。）",
    "Assoziativität": "Assoziativität bedeutet zum Beispiel $(AB)C=A(BC)$ bei der Matrixmultiplikation.（结合律表示例如矩阵乘法中有 $(AB)C=A(BC)$。）",
    "Distributivität": "Distributivität bedeutet zum Beispiel $A(B+C)=AB+AC$.（分配律表示例如 $A(B+C)=AB+AC$。）",
    "Homogenität": "Homogenität einer linearen Abbildung bedeutet $T(cu)=cT(u)$.（线性映射的齐次性表示 $T(cu)=cT(u)$。）",
    "Kommutativität": "Kommutativität gilt für die Vektoraddition, aber im Allgemeinen nicht für Matrixmultiplikation.（向量加法满足交换律，但矩阵乘法一般不满足。）",
    "Linearitätsbedingung": "Die Linearitätsbedingung besteht aus Additivität und Homogenität.（线性条件由可加性和齐次性组成。）",
    "Monotonie": "Monotonie beschreibt, ob eine Abbildung die Ordnung von Zahlen erhält.（单调性描述一个映射是否保持数的大小顺序。）",
    "Neutralität": "Neutralität bedeutet, dass ein neutrales Element wie $0$ bei Addition oder $I$ bei Matrixmultiplikation nichts verändert.（中性元性质表示加法中的 $0$ 或矩阵乘法中的 $I$ 不改变对象。）",
    "Positivität": "Positivität einer Norm bedeutet $\\|x\\|\\ge0$ und $\\|x\\|=0$ nur für $x=0$.（范数的正性表示 $\\|x\\|\\ge0$，且只有 $x=0$ 时范数为零。）",
    "Skalarmultiplikation": "Skalarmultiplikation multipliziert jeden Eintrag eines Vektors mit demselben Skalar.（数乘把向量的每个分量都乘以同一个标量。）",
    "Subadditivität": "Subadditivität der Norm ist die Dreiecksungleichung $\\|x+y\\|\\le\\|x\\|+\\|y\\|$.（范数的次可加性就是三角不等式 $\\|x+y\\|\\le\\|x\\|+\\|y\\|$。）",
    "Transitivität": "Transitivität bedeutet: Wenn $u=v$ und $v=w$, dann gilt auch $u=w$.（传递性表示若 $u=v$ 且 $v=w$，则 $u=w$。）",
})


def main():
    rows = []
    with CSV_PATH.open("r", encoding="utf-8-sig", newline="") as f:
        for row in csv.reader(f):
            if not row:
                continue
            term = row[0].strip()
            cn = row[1].strip() if len(row) > 1 else ""
            example = EXAMPLES.get(term)
            if example is None:
                example = f"In einer Rechenaufgabe sollte man {term} immer mit der passenden Definition verwenden.（做计算题时，应结合相应定义使用 {term}。）"
            rows.append([term, cn, example])
    with CSV_PATH.open("w", encoding="utf-8-sig", newline="") as f:
        csv.writer(f).writerows(rows)
    print(f"updated examples for {len(rows)} terms")


if __name__ == "__main__":
    main()
